# Generated by Django 3.1.4 on 2020-12-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=70)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Password', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=70)),
                ('Phone', models.CharField(default='', max_length=70)),
                ('Country', models.CharField(default='', max_length=70)),
                ('State', models.CharField(default='', max_length=70)),
                ('Parish', models.CharField(default='', max_length=70)),
                ('Media', models.CharField(default='', max_length=70)),
                ('item', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
